### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bortkiewicz**

### CODE REVIEW

**Comment by hanyuone** [comment]
So you're saying that stuff like `#include <iostream>` should be included by default in C++ files?

**Comment by bortkiewicz** [comment]
Yeah? And `using namespace std`and things that would be default in programs that have overhead. Unlike Python.

**Comment by hanyuone** [comment]
Hmmm, I would personally prefer that the programs be full programs, with all of the normal stuff included. You're not competing with other languages anyway, so it shouldn't matter that much.

**Comment by bortkiewicz** [comment]
Okay. I thought you saw my first pull request :P Oh well. But what about your C program? And also, I added another commit.

**Comment by hanyuone** [comment]
Yeah... will add. Do you want to be a collaborator?

**Comment by bortkiewicz** [comment]
Yes. Thanks!

**Pull request merged**
